Upgrade to Decidim 0.22.0
AjuntamentdeBarcelona/decidim-barcelona pull request #323
Opened 2020-09-07 15:40 UTC by tramuntanal

#### :tophat: What? Why?

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Remove humour GIF section from pull request template
- [ ] Upgrade gems
- [ ] Copy & execute upgrade migrations
- [ ] force ssl

### :camera: Screenshots (optional)
![Description](URL)

#### :ghost: GIF
![]()

2020-09-09 09:05 UTC, andreslucena requested changes

2020-09-09 09:05 UTC, andreslucena commented on Gemfile
> +DECIDIM_VERSION = { git: "https://github.com/decidim/decidim", branch: "release/0.22-stable" }
wouldn't it be better to point to the released version in rubygem?

2020-10-20 16:01 UTC, tramuntanal commented
ok, @ivan-mr [the fix](https://github.com/decidim/decidim/pull/6710] is already in this branch

2020-11-17 07:11 UTC, Leusev approved these changes
Ok, looks good for me @tramuntanal :+1:

2020-11-17 07:16 UTC, merged